### ISSUE TITLE
Exif value errir

### ISSUE THREAD

**Issue by Rainerino** [wchang22/GeoTag#3]
```bash

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yiyi/Documents/SkyEye/src/main.py", line 267, in <module>
    main()
  File "/home/yiyi/Documents/SkyEye/src/main.py", line 248, in main
    path_to_image, time_elapsed = take_and_tag_image(vehicle=vehicle, camera_choice= args.camera_choice, path_output_dir= IMAGE_DIR, image_count=image_counter)
  File "/home/yiyi/Documents/SkyEye/src/main.py", line 128, in take_and_tag_image
    if not geotag_image(vehicle, path_to_image):
  File "/home/yiyi/Documents/SkyEye/src/main.py", line 181, in geotag_image
    geotag.write_geo_tag(path_to_image, lat=lat, lon=lon, alt_abs=alt, hdg=hdg, roll=roll, pitch=pitch, yaw=yaw)
  File "/home/yiyi/Documents/SkyEye/src/GeoTag/geotag.py", line 258, in write_geo_tag
    metadata[tag] = pyexiv2.ExifTag(tag, value)
  File "/home/yiyi/.local/share/virtualenvs/SkyEye-ryVLLe-T/lib/python3.5/site-packages/pyexiv2/exif.py", line 103, in __init__
    self._set_value(value)
  File "/home/yiyi/.local/share/virtualenvs/SkyEye-ryVLLe-T/lib/python3.5/site-packages/pyexiv2/exif.py", line 212, in _set_value
    self.raw_value = self._convert_to_string(value)
  File "/home/yiyi/.local/share/virtualenvs/SkyEye-ryVLLe-T/lib/python3.5/site-packages/pyexiv2/exif.py", line 435, in _convert_to_string
    raise ExifValueError(value, self.type)
pyexiv2.exif.ExifValueError: Invalid value for EXIF type [Rational]: [-7/100]
```

**Comment by Rainerino** [comment]
sovled by forcing positive altitude.
